### ISSUE TITLE
Additional Hierarchical Layer for Large Organisations 

### ISSUE THREAD

**Issue by rfelber** [iteratec/TeamDojo#5]
As TeamDojo user I would like to organize teams within a large organization into departments to separate different teams more easily based on their organizational structure:

```
- root hierarchy level 1
  - hierarchy level 1
    - hierarchy level 1.1
    - hierarchy level 1.2
    - hierarchy level 1.3
      - Team A
      - Team B
      - Team C 
  - hierarchy level 2
    -  ...
  - hierarchy level 3
      - Team D
      - Team E
      - Team F 
  - hierarchy level 4
  -  ...
```
### Requirements

- team-group selector in TD Header

### Open Issues

- Are skills also related to organisations or independent? 
  - Decision: no, skills are always global for all org units.
- Are Badges also related to organisations or independent?
   - tbd (not yet)  

![image](https://user-images.githubusercontent.com/7081348/155519448-1e15b6ab-10f1-4b73-934e-de556f2bd793.png)

### Todos

- [x] Generate code for `TeamGroup`.
- [x] Remove obsolete `Organisation`.
- [x] Integrate `TeamGroup` into frontend.
