### ISSUE TITLE
Fix UI after JHipster Upgrade 7.7.0

### ISSUE THREAD

**Issue by Weltraumschaf** [iteratec/TeamDojo#81]
List of breaking changes, which still need to be checked:

- [x] Breaking Renamed color-yiq() function and related variables to color-contrast() as it’s no longer related to YIQ colorspace. See #30168. (not found via text search of "color-yiq(")
- [x] $yiq-contrasted-threshold is renamed to $min-contrast-ratio.
- [x] $yiq-text-dark and $yiq-text-light are respectively renamed to $color-contrast-dark and $color-contrast-light.
Breaking Media query mixins parameters have changed for a more logical approach.
- [x] media-breakpoint-down() uses the breakpoint itself instead of the next breakpoint (e.g., media-breakpoint-down(lg) instead of media-breakpoint-down(md) targets viewports smaller than lg).
- [x] Breaking Dropped color(), theme-color(), and gray() functions in favor of variables. See #29083.
- [x] Breaking Renamed theme-color-level() function to color-level() and now accepts any color you want instead of only $theme-color colors. See #29083 Watch out: color-level() was later on dropped in v5.0.0-alpha3.
- [x] Breaking Renamed $enable-prefers-reduced-motion-media-query and $enable-pointer-cursor-for-buttons to $enable-reduced-motion and $enable-button-pointers for brevity.
- [x] Breaking Removed the bg-gradient-variant() mixin. Use the .bg-gradient class to add gradients to elements instead of the generated .bg-gradient-* classes.
- [x] Breaking Removed previously deprecated mixins:
hover, hover-focus, plain-hover-focus, and hover-focus-active
float()
form-control-mixin()
nav-divider()
retina-img()
text-hide() (also dropped the associated utility class, .text-hide)
visibility()
form-control-focus()
- [x] Breaking Renamed scale-color() function to shift-color() to avoid collision with Sass’s own color scaling function.
- [x] Improved gutters. Gutters are now set in rems, and are narrower than v4 (1.5rem, or about 24px, down from 30px). This aligns our grid system’s gutters with our spacing utilities.
- [x] Added new gutter class (.g-*, .gx-*, and .gy-*) to control horizontal/vertical gutters, horizontal gutters, and vertical gutters.
- [x] Breaking Renamed .no-gutters to .g-0 to match new gutter utilities.
- [x] Breaking .thead-light and .thead-dark are dropped in favor of the .table-* variant classes which can be used for all table elements (thead, tbody, tfoot, tr, th and td).
- [x] Breaking The table-row-variant() mixin is renamed to table-variant() and accepts only 2 parameters: $color (color name) and $value (color code). The border color and accent colors are automatically calculated based on the table factor variables.
- [x] Breaking Removed hover and focus styles for <a> and <button> elements.
- [x] Breaking Dropped .btn-block for utilities. Instead of using .btn-block on the .btn, wrap your buttons with .d-grid and a .gap-* utility to space them as needed. Switch to responsive classes for even more control over them. Read the docs for some examples.
- [x] Breaking Replaced the .card based accordion with a new Accordion component.
- [x] Breaking Dropped the jumbotron component as it can be replicated with utilities. See our new Jumbotron example for a demo.
- [x] Breaking Navbars now require a container within (to drastically simplify spacing requirements and CSS required).
- [x] Breaking Removed .text-hide as it’s an antiquated method for hiding text that shouldn’t be used anymore.

Issues seems we're not affected by:

- Breaking Removed print styles and $enable-print-styles variable. Print display classes are still around. See #28339.
- Similarly, the second parameter in media-breakpoint-between() also uses the breakpoint itself instead of the next breakpoint (e.g., media-between(sm, lg) instead of media-breakpoint-between(sm, md) targets viewports between sm and lg).
- Breaking bootstrap-grid.css now only applies box-sizing: border-box to the column instead of resetting the global box-sizing. This way, our grid styles can be used in more places without interference.
- Breaking Overhauled our display typography to replace our $display-* variables and with a $display-font-sizes Sass map. Also removed the individual $display-*-weight variables for a single $display-font-weight and adjusted font-sizes.
- Breaking Nested tables do not inherit styles anymore.
- Breaking .text-* utilities do not add hover and focus states to links anymore. .link-* helper classes can be used instead. See #29267
- Breaking Form labels now require .form-label.
- Breaking .form-text no longer sets display, allowing you to create inline or block help text as you wish just by changing the HTML element.
- Breaking Toggle buttons, with checkboxes or radios, no longer require JavaScript and have new markup. We no longer require a wrapping element, add .btn-check to the <input>, and pair it with any .btn classes on the <label>. See #30650. The docs for this has moved from our Buttons page to the new Forms section.
- Breaking All the events for the dropdown are now triggered on the dropdown toggle button and then bubbled up to the parent element.
- Breaking Dropped flip option for dropdown plugin in favor of native Popper configuration. You can now disable the flipping behavior by passing an empty array for fallbackPlacements option in flip modifier.
- Breaking The default value for the fallbackPlacements is changed to ['top', 'right', 'bottom', 'left'] for better placement of popper elements.
- Breaking Disabled negative margins by default.
- Breaking Responsive embed helpers have been renamed to ratio helpers with new class names and improved behaviors, as well as a helpful CSS variable.
Classes have been renamed to change by to x in the aspect ratio. For example, .ratio-16by9 is now .ratio-16x9.
We’ve dropped the .embed-responsive-item and element group selector in favor of a simpler .ratio > * selector. No more class is needed, and the ratio helper now works with any HTML element.
The $embed-responsive-aspect-ratios Sass map has been renamed to $aspect-ratios and its values have been simplified to include the class name and the percentage as the key: value pair.
CSS variables are now generated and included for each value in the Sass map. Modify the --bs-aspect-ratio variable on the .ratio to create any custom aspect ratio.
- Breaking “Screen reader” classes are now “visually hidden” classes.
Changed the Sass file from scss/helpers/_screenreaders.scss to scss/helpers/_visually-hidden.scss
Renamed .sr-only and .sr-only-focusable to .visually-hidden and .visually-hidden-focusable
Renamed sr-only() and sr-only-focusable() mixins to visually-hidden() and visually-hidden-focusable().
- Breaking Data attributes for all JavaScript plugins are now namespaced to help distinguish Bootstrap functionality from third parties and your own code. For example, we use data-bs-toggle instead of data-toggle.
